name: On Push or Pull to main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:      
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
   
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
       versionSpec: '5.x'
        
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7

    - run: echo ${{ env.GITVERSION_NUGETVERSIONV2 }}

    - run: |
        echo github.ref
        echo "GITHUB_REF#refs/*/:" ${GITHUB_REF#refs/*/}
        echo "GITHUB_REF#refs/heads/:" ${GITHUB_REF#refs/heads/}
        echo "GITHUB_REF#refs/tags/:" ${GITHUB_REF#refs/tags/}
        echo "GITHUB_WORKFLOW:" ${GITHUB_WORKFLOW}
        echo "GITHUB_RUN_ID:" ${GITHUB_RUN_ID}
        echo "GITHUB_RUN_NUMBER:" ${GITHUB_RUN_NUMBER}
        echo "GITHUB_JOB:" ${GITHUB_JOB}
        echo "GITHUB_ACTION:" ${GITHUB_ACTION}
        echo "GITHUB_ACTION_PATH:" ${GITHUB_ACTION_PATH}
        echo "GITHUB_ACTIONS:" ${GITHUB_ACTIONS}
        echo "GITHUB_ACTOR:" ${GITHUB_ACTOR}
        echo "GITHUB_REPOSITORY:" ${GITHUB_REPOSITORY}
        echo "GITHUB_EVENT_NAME:" ${GITHUB_EVENT_NAME}
        echo "GITHUB_EVENT_PATH:" ${GITHUB_EVENT_PATH}
        echo "GITHUB_WORKSPACE:" ${GITHUB_WORKSPACE}
        echo "GITHUB_SHA:" ${GITHUB_SHA}
        echo "GITHUB_REF:" ${GITHUB_REF}
        echo "GITHUB_HEAD_REF:" ${GITHUB_HEAD_REF}
        echo "GITHUB_BASE_REF:" ${GITHUB_BASE_REF}
        echo "GITHUB_SERVER_URL:" ${GITHUB_SERVER_URL}
        echo "GITHUB_API_URL:" ${GITHUB_API_URL}
        echo "GITHUB_GRAPHQL_URL:" ${GITHUB_GRAPHQL_URL}
        echo "RUNNER_NAME:" ${RUNNER_NAME}
        echo "RUNNER_OS:" ${RUNNER_OS}
        echo "RUNNER_TEMP:" ${RUNNER_TEMP}
        echo "RUNNER_TOOL_CACHE:" ${RUNNER_TOOL_CACHE}
        cat ${GITHUB_EVENT_PATH}
